language: objective-c
osx_image: xcode9.3

branches:
 only:
 - master

script:
- xcodebuild clean build -sdk iphonesimulator -project KAProgressLabel.xcodeproj -scheme KAProgressLabel CODE_SIGNING_REQUIRED=NO
